apiVersion: v2
name: oadp-operator
description: A Helm chart for oadp-operator
type: application
dependencies:
  - name: stakater-operators-installer
    repository: oci://ghcr.io/stakater/saap-catalog/charts
    version: 1.0.0
version: 1.0.0

appVersion: "0.0.0"
