operators-installer:
  operators:
    - channel: stable-1.3
      installPlanApproval: Automatic
      name: redhat-oadp-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      csv: oadp-operator.v1.3.1
      namespace: openshift-adp

  operatorGroups:
    - createNamespace: true
      name: openshift-adp
      targetOwnNamespace: true
      otherTargetNamespaces: []
