# -- Put here the new name if you want to override the release name.
nameOverride: ""

# -- Same as nameOverride but for the fullname.
fullnameOverride: ""

# -- Same as nameOverride but for the namespace.
namespaceOverride: ""