namespace: reloader-demo

image:
  repository: ghcr.io/linuxcontainers/alpine
  tag: "3.20"
  pullPolicy: IfNotPresent

configUpdater:
  enabled: true
  schedule: "*/2 * * * *"

secretUpdater:
  enabled: true
  schedule: "*/3 * * * *"

workloadGenerator:
  enabled: true
  schedule: "*/10 * * * *"
