{{- if and .Values.tenant .Values.tenant.enabled }}
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: {{ .Values.tenant.name }}                        # Chose the desired name
  namespace: {{ .Release.Namespace }}
spec:
{{- if .Values.tenant.probes }}
  probes:
{{- toYaml .Values.tenant.probes | nindent 4 }}
{{- end }}
  size: {{ .Values.tenant.size }}                               # Adjust to your requirements
  replicas: {{ .Values.tenant.replicas }} 
{{- if .Values.tenant.scheduling }}
  scheduling:
{{- toYaml .Values.tenant.scheduling | nindent 4 }}
{{- end }}
  ingress:
    enabled: {{ .Values.tenant.ingress.enabled }} 
    host: {{ .Values.tenant.ingress.host }}        # Adjust to your domain
    annotations:
      kubernetes.io/ingress.class: nginx
  version: 7.4.0
  licenseSecret: {{ .Values.tenant.licenseSecret }}                              # If you have created secret in step 1, put its name here
{{- if .Values.tenant.database.external }}
  database:
    external:
      secret: {{ .Values.tenant.database.secretName }}      # Name of a Kubernetes secret that contains connection string to external database.
{{- end }}
{{- if .Values.tenant.fileStore.external }}
  fileStore:
    external:
      url: {{ .Values.tenant.fileStore.url }}
      bucket: {{ .Values.tenant.fileStore.bucket }}
      secret: {{ .Values.tenant.fileStore.secretName }}
{{- end }}
{{- end }}
