{{- if .Values.instance.enabled }}
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: splunk
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  volumes:
    - name: apps
      configMap:
        name: splunk-apps
  defaults: |-
    splunk:
      apps_location:
        - "/mnt/apps/app1.tgz"
        - "/mnt/apps/app2.tgz"
{{- end }}
