apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    name: splunk-operator
  name: splunk-operator-controller-manager-metrics-service
  namespace: splunk-operator
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
    name: splunk-operator
