## Take connection string or uri from postgres-pguser-documentservice-user secret and use postgres instead of postgresql in the beginning to avoid uri error
## https://github.com/mattermost/mattermost-operator/issues/269
{{- if .Values.tenant.database.external }}
{{- if .Values.tenant.database.sealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.tenant.database.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    DB_CONNECTION_STRING: {{ .Values.tenant.database.connectionString }} 
  template:
    metadata:
      name: {{ .Values.tenant.database.secretName }}
      namespace: {{ .Release.Namespace }}
{{ else }}
apiVersion: v1
data:
  DB_CONNECTION_STRING: {{ .Values.tenant.database.connectionString }} 
kind: Secret
metadata:
  name: {{ .Values.tenant.database.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
{{- end }}
