{{- if and .Values.tenant.route .Values.tenant.route.enabled }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.tenant.route.name }} 
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.tenant.route.host }} 
  to:
    kind: Service
    name: {{ .Values.tenant.name }} 
    weight: 100
  port:
    targetPort: app
{{- if .Values.tenant.route.tls }}
  tls:
{{- toYaml .Values.tenant.route.tls | nindent 4 }}
{{- end }}
  wildcardPolicy: None
{{- end }}
