{{- $alert := "CNPGClusterPGDatabaseXidAgeWarning" -}}
{{- if not (has $alert .excludeRules) -}}
alert: {{ $alert }}
annotations:
  summary: Number of transactions from the frozen XID to the current one
  description: Over 300,000,000 transactions from frozen xid on pod {{ .labels.pod }}
expr: cnpg_pg_database_xid_age > 300000000
for: 5m
labels:
  severity: warning
  namespace: {{ .namespace }}
  cnpg_cluster: {{ .cluster }}
{{- end -}}
