{{- if .Values.instance.enabled }}
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: splunk
  namespace: splunk-operator
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  volumes:
    - name: defaults
      configMap:
        name: splunk-defaults
  defaultsUrl: /mnt/defaults/default.yml
{{- end }}
