{{- if and ( .Values.metrics.clusterRole ) ( .Values.metrics.clusterRole.enabled ) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
{{- end }}
