{{- if and ( .Values.metrics.clusterRole ) ( .Values.metrics.clusterRole.enabled ) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: splunk-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: splunk-operator-controller-manager
  namespace: splunk-operator
{{- end }}
