nameOverride: ""

fullnameOverride: ""

namespaceOverride: ""

grafana:
  folder: "Vault dashboard"
  instanceSelector:
    matchLabels:
      app: "grafana"

  # Default datasources for the dashboard
  datasources:
    - inputName: "DS_PROMETHEUS"
      datasourceName: Prometheus
