{{- if and ( .Values.podMonitor ) ( .Values.podMonitor.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{- include "keycloak-observability.name" . | indent 1 }}-pod-monitor
  namespace: {{- include "keycloak-observability.namespace" . | indent 1 }}
  labels:
    {{- include "keycloak-observability.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.podMonitor.specs | nindent 2 }}
{{- end }}