global:
  namespace:
grafana:
  labels:
    grafanaDashboard: grafana-operator
  resourceUtilization:
    enabled: true
prometheus:
  rules:
    resource:
      requestMemoryUnderCommited:
        enabled: true
        # threshold in Mb 
        threshold: 500
      requestMemoryOverCommited:
        enabled: true
        # threshold in Mb 
        threshold: 500