global:
  namespace:

grafana:
  labels:
    grafanaDashboard: grafana-operator
  resourceUtilization:
    enabled: true
prometheus:
  rules:
    resource:
      requestMemoryUnderCommited:
        enabled: true
        # threshold in Mb 
        treshold: 500
