# a comment
global:
  namespace:

# Grafana instance selector
grafana:
  resourceUtilization:
    enabled: true
  matchLabels:
    dashboards: "grafana"

# Default data sources
dashboard:
  datasources:
    - inputName: "DS_PROMETHEUS"
      datasourceName: "Prometheus"

prometheus:
  rules:
    resource:
      requestMemoryUnderCommited:
        enabled: true
        # threshold in Mb 
        threshold: 500
      requestMemoryOverCommited:
        enabled: true
        # threshold in Mb 
        threshold: 500
