load('ext://namespace', 'namespace_create', 'namespace_inject')

settings = read_json('../tilt-settings.json', default={})

namespace= "openshift-adp"

if settings.get("default_registry"):
  default_registry(settings.get("default_registry").format(namespace), host_from_cluster='image-registry.openshift-image-registry.svc:5000/{}'.format(namespace))

if settings.get("allow_k8s_contexts"):
  allow_k8s_contexts(settings.get("allow_k8s_contexts").format(namespace))

namespace_create(namespace)

yaml=helm(
         '.',
         name='oadp-instance',
         namespace=namespace,
         values=['values-local.yaml'])

print(yaml)

k8s_yaml(yaml)
