# Default values for mattermost-instance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  createNamespace: false
  labels:
    stakater.com/tenant: gabbar

tenant:
  enabled: true
  name: stakater-mattermost
  route:
    enabled: true
    name: stakater
    host: stakater-mattermost-instance.apps.devtest.vxdqgl7u.kubeapp.cloud
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  licenseSecret: ""
  database:
    external: true
    secretName: mattermost-postgres-connection
    connectionString: cG9zdGdyZXM6Ly9kb2N1bWVudHNlcnZpY2UtdXNlcjpPbnpLRSU3REhFTSU1RTJRbmklN0JOJTI5PUclN0IubDRUQHBvc3RncmVzLXByaW1hcnkubWF0dGVybW9zdC1pbnN0YW5jZS5zdmM6NTQzMi9kb2N1bWVudHNlcnZpY2UtZGI=
  fileStore:
    external: true
    url: http://minio.mattermost-instance.svc:80
    bucket: test
    secretName: minio-creds-secret
  ingress:
    enabled: false
    host: stakater-mattermost-instance.apps.devtest.vxdqgl7u.kubeapp.cloud
  size: 500users                               # Adjust to your requirements
  replicas: 2
  scheduling:
    resources:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 500Mi 
  probes:
    livenessProbe:
      httpGet:
        path: /api/v4/system/ping
        port: 8065
        scheme: HTTP
      initialDelaySeconds: 20
      timeoutSeconds: 60
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /api/v4/system/ping
        port: 8065
        scheme: HTTP
      initialDelaySeconds: 20
      timeoutSeconds: 60
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 6
