# Default values for mattermost-instance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  createNamespace: false
  labels:
    stakater.com/tenant: gabbar

tenant:
  enabled: true
  name: stakater-mattermost
  route:
    enabled: true
    name: stakater
    host: stakater-mattermost-instance.apps.devtest.vxdqgl7u.kubeapp.cloud
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  licenseSecret: ""
  database:
    external: true
    sealedSecret: true
    secretName: mattermost-postgres-connection
    connectionString: AgCHEddZlZgRm2NF+AD4e9ZTR82kyVsNDFwApmZm5BqeGWpDYtK+DCi0a767agAjwRR3mdpxzvpQKgmjz4I9yFI1sLzjr1N8AlcPKDtKDt+iD7NOX/C7mALo3qXeuRbc/YQQyyCODVzo9ob/WMDD1szXOb0QXAhO51DxFQTK06ql/elnisSwh5kKjKBRZzAx7kMEVYJ+awqIEOtJs5p+l6xtpfE1DJHB6eNrHXnw/jecM87H7DXH26+4zdCNf4Bb7aZxHbnTVmj3PUgXOFz2j/+x84glUWNXnBKALSKzP/wA5OYAMl1AH+NcOqQX8S/UOg5POb3tCxa8+ac8IJw8lBxTtl6ipk+sD1rEdnDB894iTUWxhkEDUuzTBtDGxB85AgT7J/JFrcQbhdbyCnEV5vWs7La7eJcJT7siGPZS1tN3S/c9xtw9kdNOqEAzmUf4bmvN9mALgF6lbddyGSDBMu5TcvCxgntHYk4eg5NCZK8+tdgdHwjJdNqRs8J+PpfwbjYgY9IDZYymy+qG4yR4OUFfMCIjhWGn7qIIhunWe0NfkawESFKWQYIFf05oOkkWSlmWOZqDkr8Kkn83amFRA05Wev7DyRb4PjTKf5ejMdxCF/vE8QzuYk2ZDvod+xvRgx/Ma6qj/YSMNfLWMmD33vxbW1DNDPWVv0FNJDxwnUXM1ZTDTbZY13Vn+EsIj5aUMOo61Q+Lj4nOQ/EFa6m4ECgv8svWb+BTqSjx1ZVDoVKw4fjh83uyJF2YZzvDqJutaNHaVmuMgZaLe2UVIpzzdA+OorXMaifz4FbxD/eHDmVOYJjn10OfiLgcsrH3oVuWxVc8UgPC65Vhm4YXhAlOGF/yp7399nIuoiFRfl7RoFr6XXp8Tw==
  fileStore:
    external: true
    url: http://minio.mattermost-instance.svc:80
    bucket: test
    secretName: minio-creds-secret
  ingress:
    enabled: false
    host: stakater-mattermost-instance.apps.devtest.vxdqgl7u.kubeapp.cloud
  size: 500users                               # Adjust to your requirements
  replicas: 2
  scheduling:
    resources:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 500Mi 
  probes:
    livenessProbe:
      httpGet:
        path: /api/v4/system/ping
        port: 8065
        scheme: HTTP
      initialDelaySeconds: 20
      timeoutSeconds: 60
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /api/v4/system/ping
        port: 8065
        scheme: HTTP
      initialDelaySeconds: 20
      timeoutSeconds: 60
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 6


minio-operator:
  secret:
    enabled: false
  sealedSecret:
    enabled: true
    labels: 
      # key: value
    annotations: 
      # key: value
    files:
    - name: console-secret
      encryptedData:
        CONSOLE_ACCESS_KEY: AgA6jYpKJANk6z+IqBFt7F+qOKnXnw4pcgrPFuzQWNbrHulVneAoDG0+ZeORzQY/8Latp/QcPS03kcD5LtCIAmeXjW2djjcG93y/fLAQqcGAqBD56u95lZ8yIUcIGUBoQ3cp4O7XVy3MmkOj1vVfBPVs57xPmq+OLZTeAix9E8rDkTU25MXbWfHgGlGwJ+ly4zhBXVYJJAmw+FBTbxcSPk6ougS9zcTL1nqdYftfiJzn/YtYvS14wSovrRy3pC6gwa9yq/WqjCn6nhbSYlrZbipgcC6icWEXccRggTC2RcrHp3MkSBcrXNUDYxTpkxX0Aygq2Cc3pvYZUO5XJO5smR7TgY2a6zI8GWUmrRwLU1FNb4sf8N/zbzF+r1CPwDyMHq3pvfTGbM+xnIK63KF3EEUqFrGn5PhifSw5w+nEOyxrwfU+EZ+wdtv7oTba5eY53cT/4XyuHYjtPQLl8qqmU9ZqezpMBR+5YeFHRrUMd9xRWamUE/7goyBMUO4AL4Oqn2TY1ku8DP9v0HI9uaMxPV4k3sp9Y08a4qgDI2gPJwkeuU2aYh/gcnrsBf8Vy5nCfgGkWKgbtyc0V7yWcLSeGpTUbN0rUCuFPs1nnRY1VMf6stu8hAeN4YXDUsGU+aWzKP6juRrzJ7pYoKoTwf3pD9I+6JOX0UQkdDYAYNgw1z39zu3fXdDCyWwO0IJ2587gbHAcJm+1tw==
        CONSOLE_PBKDF_PASSPHRASE: AgBh2vq4GrBCPiS1EHCMlnDGRNECvPchOEsrCMzlsnM8632mgSjMt475fPK8iJ8ZBBUZHlIMEffJjitEQgg1UAPPrenrdEFBvSlqgFnhHlloYNZMxrWRUNp84H+2N0wiLDIJ9sYIcubFk0RS+ONOPIA92dts/cAEuIGTb4r+NtBPgdOxKLLL6+yTcaVcYNCkxWGZSx6VFFARW66JHWIk0+W/9aBM4y9MsuRgeM3yuivabtKlK31IFtiwhdYgqsvtbqXGD4u4NtTMaN5pwYg15eC8sJo2/GAxeNhFwUNlqRpRsRzit8RD8molVRK8A5/BrrpR2nXFEEXkdrhDuy2iK4FtNUThEigVKrGBR6kz/jtt/yPfLaYbqZrcKxjmGSPcSHD+zckalHdqFxGErkvjHOw5Wd6rt5z7f/EbuuQtipn2KI4miRXxj/nN6GYpwjLW6dQeuY9bfR7eWrUJAt9z31nz4X89GwbzoYEmbeh8KnklUkR0OGyTAE1j/ts5Kboff31eJ9P/gpukNCAebhjmdoh7wnh7m+nZ/lNrU0kkBYEa9NhW5Vf9zFZP48IFEpgJct3k1tOZKyH8+pydZHtapxiWrRUt9X+zJd1WXDPQwaJsQpQw0yxunEaIgFe30+iQbKyrKmvuTtdDKmnyzKMFJVLoJlfYkUxu4i682Qa9gV6q8hRDhvLu1WCpl8/hVaBYO95WvUE4Kg==
        CONSOLE_PBKDF_SALT: AgBmTTtojHh6nFnNX2VYgx7sI8j5EcQKxFq2YMLIO9ttGFBkeoPjJvsVPHG1N23jh2Oz2nk03BmdYjdbeflZeJg9/vj40tphVhr17fNyoCdomI+MGby92vc/hcev2AjQqzM47iFIiq/IyaDe8F/Fwjxf/hPPkX8nsEysVtIfweyfW70nnMVxDSsgrsYZSqfsuSQb8cfni5tiL16Rb/m5NeoARqsY65KT6Ew61/HIfdL+3g8WNsaqXU/zJl4EezjlpHCQKPDynTI+lp1drJYW8zulB2JpT5ofSmSL41yJ1lka8wH9hdhGAaztf4baQdNbSbClW7lbBWKPCfG9MW0vQzlN0eCOD3GdcCz/1woOxErcypzfsXtUVJBFuFz0fAtXIY8iEpQ9FaQDjKsLCEHgQ4oRefMHsXl8p99XGqAi+R7gvvBm0GPxXRZHPLGyOY/nbNmIXo9H5pcjdr6t3yH5+sUB5O17OVVWlYiKJgZsQmyhSyOOZ0MzSisyT0aHQdTX+4zIqBhFasp154CUrB4oA/3EQhpZFdiKPtKTFhz2RoBuFkaFBxlvm8Rwpz3k/hMSymhb56KtMjZAZ4HJNODrdu6BuhQG9o6Mf8Ib+6uvq7kFJQ9vvctsIS/YT/MCzk38u7tTIFIUbAWH7DEQWQsPm3cNMhR1YjIY1C2Kyj2mxzXktQjNEOLL644DUETMmo1ppSbW66OiTg==
        CONSOLE_SECRET_KEY: AgAnyb7DRe1gw31ReazAfw1ScJmnqRCmGtOz0kv8i4v/NM3fTUdgvmMnByl7s9po3FSSwSSOaln13fFN5Enm8Z0RhplW4NbLyxbV4p/v+s84gBRg1SAo7BRclU82msMt6IOldNslHKZv6qF7pb+Z3diQhXpK6mvVRUxJeY/mmBvfE1issLrtaNaJsicisP7faWp894AsV/6enW6PMt9HHe1epwveVKpBlIfLuuF7SmhSiK6MqhT4evzO84Eld2LzScwcrmAnLz1QdnQCYG42KBAbMgKO8r6CpC7b/G2e1FE1QpxdhZq3dQxxivUjLW/nFQqJw1Pid89Ds0zbvFwfIP9AsPT91BNbDNkfjDKw1E1uUI0TurzvSZxZoMs4AUY3rF5LH2Eh1ivJfvr2Tk6+/1pY+npHzEQpMQyqo1w8MJ+hJ+bZKGnbwojYxsXkcNXcgyGPnX72FBKIjPcShxuvVJQwxA5W2iiiibE+YVx6rVqWTa1BFEjGUMrcg7YMcFi9aWTusBMbKHJucCGGfsGHpJJJBlIQy8bQgY3NN7yILb4UlggxkNVExRXIG4xnXOi2eknxEPxLar+hLwUZnmJ+SWXstvKIfCIGI3nF92wslzpHvsGYWBoGWD5aY3KdhL0uJQbGx6tCtTJ7lLGcA8UeBPK8tudZNgIGAYBu7IZtFkW6KOTdTVIbxMUe0iYZ6b88CriZ9CQDcA==
    - name: minio-creds-secret
      encryptedData:
        accesskey: AgCEGU9TgW79VKGB/kTZmC+iEoBTF6KLs6lnqDmEwvNYAT7HEEdPk4Dcxk0Q/4WWW6TS67NPDm+5mSw+1yunZwHVgliW361gX4xnn2U1etPW40QkWgji/FVlgOYkF57YsBQNS2AjSFKO0iGlUNPQG7QfEU8HtuTqfqF70w6xqUFXFRvuiGVO9wGT5XiSFfsOJu+oxbUvC1fo57u2UUK7sn5eQIFxQiNu1ZvSnGdw6p63pcJSpWtLiRpe0Zplv7hASGj8mRpGYj+z2i/sWs+El9Hp8xCDSCkOrWbXTARm1TBJKoSUz2lJeQ5TZPSzfztSwWb7upQlNveX8DbUWw6N8eAwmTEmGt/46CPZR5o2m4qUy815xCn7k50kEiSw7sHNywjNEXiZvEf6P0NFUSz4Gg9lj2LhzjfyKIo6NphtOQV7AYmny+OACJ50s+InKH17eJMaaf3/HJroOF60/6ZABHHULpZJYmDjAFkLSOR9J3/7GkBW2K51Kqz+bXhySWaBurtEWpnrPzK8Ri6ncOhhU4CUzCGn5QHesludr275E4EpjD/L509nGMNB1GZRVY1AZQCf3dkjrkqe6RcFvTInCNzE3KThpSXIEckN4xgFAVgoQ8gXwQfWcqItL9F4aHFppPDFI6cns+Xy9aOxB0R4ha8bo44+/jgZF/geLSgc8B3s7HB4W7NHuy9RantNo4K0LWL/LCfzBg==
        secretkey: AgADlyacndHSHnza6okE06420z3cOV90R1IzSKeA0up657tybGv6hWGhcHxt2XtZJtT5NtDjUwlYKLftqeDkwrXUEpUR5SlHkx8ey2Ws1iTr/1z+LuAOEVGz6D/epTXnO+Og28DNwudFc51jYSJu6GssY428dAafQcubACj8EdoSfyowHXx3Ibo+9p19aEgSgMdNO55GtwNSU32VrNbgNwDPJf7IsiX392u1j9Qfgpwgrff/fJXbx0vUYAhQ37jpFsWBOoMAudZymv8ed7fVX9W5xFLXar0jKnmo5cXSCuLlQxB/pumU/3Slm0vjPrljkmQbsd1RY8V/XFmG9HktRH3rLdNaYgQF9zVfUF7oue+b+lPF/wih9RQcR9JAk/LJYLY4r1Kph9wn2SC+izTDSGADGO8pLPPwhmC55XowhQrqWtqxtiSkCMz3vpF9eRdOvjKJ3Px4g/31aFgOZ1oFkJVbIammRvzWGYtwZSlcrWfd9AG3uCnJWa/RCENN1ukUByLyyBuzFRFjjFAjwOoqN9pYUDBPp4ef1eUtHvkQkQZhXINQUAarM036QKgMUtYOirxlaWH/JCl7uMgOexGPXzFnxIC2SPwGDDjyqam5dX6nvjXbrby4d0EyMdL8kp6YP3m7ogP65UZj89lLKZsOymn0jc+xPs+0dq4gOwRG9vX4VEVsLTpT/5M0yg9Vlj1KHi6UZmVYKUkOTQ==
