apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "template-operator.fullname" . }}-prometheus-k8s-role
  labels:
    control-plane: controller-manager
  {{- include "template-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - services
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "template-operator.fullname" . }}-prometheus-k8s-rolebinding
  labels:
    control-plane: controller-manager
  {{- include "template-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "template-operator.fullname" . }}-prometheus-k8s-role'
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: '{{ .Release.Namespace }}'
