---
apiVersion: v1
kind: Secret
metadata:
  # The name must follow the following format where ((ALERTMANAGER_NAME)) is the name of the Alertmanager CRD object:
  # (see https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/alerting.md#manually-managed-secret)
  name: alertmanager-{{ .Release.Namespace }}-alertmanager
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    alert_manager: "true"
    {{- include "slo-observability.labels" . | nindent 4 }}
type: Opaque
stringData:
  alertmanager.yaml: |-
    route:
      # This config notifies only on SLO alerts.
      receiver: 'null'
      routes:
      - matchers:
          - severity=~"critical|warning|none"
        receiver: slack
    receivers:
    - name: 'null'
    - name: slack
      slack_configs:
      - channel: "{{ .Values.prometheus.slack.channel }}"
        api_url: https://slack.com/api/chat.postMessage
        http_config:
          authorization:
            credentials: "{{ .Values.prometheus.slack.token }}"
        send_resolved: true
        title: '{{`{{ .Status | toUpper }}`}}{{`{{ if eq .Status "firing" }}`}}:{{`{{ .Alerts.Firing | len }}`}}{{`{{ end }}`}}'
        text: |-
          🌐 Namespace: `{{`{{ (index .Alerts 0).Labels.namespace }}`}}`

          {{`{{ range .Alerts }}`}}
           ----------------------------------------------
           🚨 Alert Name: `{{`{{ .Labels.alertname }}`}}`
           ℹ️ Description: {{`{{ .Annotations.description }}`}}
           💡 Summary: {{`{{ .Annotations.summary }}`}}
           🏷️ Labels:
           {{`{{ range .Labels.SortedPairs }}`}}• {{`{{ .Name }}`}}: `{{`{{ .Value }}`}}`
           {{`{{ end }}`}}
          {{`{{ end }}`}}
