# Dashboard name
name: rhsso

# Grafana instance selector
grafana:
  matchLabels:
    dashboards: "grafana"

# Default data sources
datasources:
  - inputName: "DS_PROMETHEUS"
    datasourceName: "Prometheus"
