
{{- range .Values.operatorGroups }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .name | default $.Release.Namespace }}
  namespace: {{ .name | default $.Release.Namespace }}
  labels:
    {{- include "operators-installer.labels" $ | nindent 4 }}
spec:
  {{- $hasOtherTargetNamespaces := and .otherTargetNamespaces (gt (len .otherTargetNamespaces) 0) }}
  {{- if or .targetOwnNamespace $hasOtherTargetNamespaces }}
  targetNamespaces:
  {{- if .targetOwnNamespace }}
  - {{ .name |  default $.Release.Namespace }}
  {{- end }}
  {{- if .otherTargetNamespaces }}
  {{- range $otherTargetNamespace := .otherTargetNamespaces }}
  - {{ $otherTargetNamespace }}
  {{- end }}
  {{- end }}
  {{- end }}
  upgradeStrategy: {{ .upgradeStrategy | default "Default" }}
{{- end }}
