
{{- range .Values.operatorGroups }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .name | default $.Release.Namespace }}
  namespace: {{ .name | default $.Release.Namespace }}
  labels:
    {{- include "operators-installer.labels" $ | nindent 4 }}
{{- $hasOtherTargetNamespaces := and .otherTargetNamespaces (gt (len .otherTargetNamespaces) 0) }}
{{- $hasTargetNamespaces := or .targetOwnNamespace $hasOtherTargetNamespaces }}
{{- $hasUpgradeStrategy := .upgradeStrategy }}
{{- if or $hasTargetNamespaces $hasUpgradeStrategy }}
spec:
  {{- if $hasTargetNamespaces }}
  targetNamespaces:
    {{- if .targetOwnNamespace }}
    - {{ .name | default $.Release.Namespace }}
    {{- end }}
    {{- if $hasOtherTargetNamespaces }}
    {{- range .otherTargetNamespaces }}
    - {{ . }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- if $hasUpgradeStrategy }}
  upgradeStrategy: {{ .upgradeStrategy }}
  {{- end }}
{{- else }}
spec: {}
{{- end }}
{{- end }}
