{{- if and ( .Values.prometheus.rules.rabbitmq.noMajorityOfPodsReady ) ( .Values.prometheus.rules.rabbitmq.noMajorityOfPodsReady.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rabbitmq-no-majority-of-pods-ready
{{- if .Values.prometheus.rules.rabbitmq.noMajorityOfPodsReady.namespace  }}
  namespace: {{ .Values.prometheus.rules.rabbitmq.noMajorityOfPodsReady.namespace }}
{{- else }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
{{- end }}
  # If labels are defined in spec.ruleSelector.matchLabels of your deployed Prometheus object, make sure to include them here.
  labels:
    role: alert-rules
{{- if .Values.prometheus.rules.labels }}
{{- toYaml .Values.prometheus.rules.labels | nindent 4 }}
{{- end }}
spec:
  groups:
  - name: rabbitmq
    rules:
    - alert: noMajorityOfPodsReady
      expr: |
        sum(up{job=~".*rabbitmq.*"}) < {{ .Values.prometheus.rules.rabbitmq.noMajorityOfPodsReady.totalPods }} / 2
      for: 5m
      annotations:
        description: |
          Only `{{`{{ $value }}`}}` pods are ready in StatefulSet `{{`{{ $labels.statefulset }}`}}`
          of RabbitMQ cluster `{{`{{ $labels.label_app_kubernetes_io_name }}`}}` in namespace `{{`{{ $labels.namespace }}`}}`.
        summary: |
          No majority of pods have been ready for the last 5 minutes.
          Check the details of the pods:
          `kubectl -n {{`{{ $labels.namespace }}`}} describe pods -l app.kubernetes.io/component=rabbitmq,app.kubernetes.io/name={{`{{ $labels.label_app_kubernetes_io_name }}`}}`
      labels:
        rabbitmq_cluster: '{{`{{ $labels.label_app_kubernetes_io_name }}`}}'
        rulesgroup: rabbitmq
        severity: warning
{{- end }}
