{{- if and ( .Values.prometheus.rules.rabbitmq.rabbitMqDiskUsageHigh ) ( .Values.prometheus.rules.rabbitmq.rabbitMqDiskUsageHigh.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rabbitmq-disk-usage-high
{{- if .Values.prometheus.rules.rabbitmq.rabbitMqDiskUsageHigh.namespace  }}
  namespace: {{ .Values.prometheus.rules.rabbitmq.rabbitMqDiskUsageHigh.namespace }}
{{- else }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
{{- end }}
  # If labels are defined in spec.ruleSelector.matchLabels of your deployed Prometheus object, make sure to include them here.
  labels:
    role: alert-rules
{{- if .Values.prometheus.rules.labels }}
{{- toYaml .Values.prometheus.rules.labels | nindent 4 }}
{{- end }}
spec:
  groups:
  - name: rabbitmq
    rules:
    - alert: RabbitMqDiskUsageHigh
      expr: rabbitmq_disk_space_available_bytes < 1073741824
      for: 1m
      annotations:
        description: RabbitMQ {{`{{ $labels.instance }}`}} available disk space < 1Gb
        summary: RabbitMQ Node has less than 1Gb disk space avaiable.
      labels:
        rabbitmq_cluster: '{{`{{ $labels.label_app_kubernetes_io_name }}`}}'
        rulesgroup: rabbitmq
        severity: critical
{{- end }}