{{- if and ( .Values.prometheus.rules.postgresTooManyConnections ) ( .Values.prometheus.rules.postgresTooManyConnections.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
    {{- include "postgres-observability.labels" . | nindent 4 }}
{{- if .Values.prometheus.rules.labels }}
{{- toYaml .Values.prometheus.rules.labels | nindent 4 }}
{{- end }}
  name: postgres-too-many-connections
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  groups:
  - name: postgres
    rules:
    - alert: PostgresTooManyConnections
      expr: sum by (datname) (pg_stat_activity_count{datname!~"template.*|postgres"}) > pg_settings_max_connections * 0.9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Postgresql too many connections (instance {{`{{ $labels.instance }}`}} in cluster {{`{{$labels.cluster_name}}`}})
        description: "PostgreSQL instance has too many connections\n  VALUE = {{`{{ $value }}`}}\n  LABELS: {{`{{ $labels }}`}}"
{{- end }}
