{{- if and ( .Values.prometheus.rules.postgresNotEnoughConnections ) ( .Values.prometheus.rules.postgresNotEnoughConnections.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
    {{- include "postgres-observability.labels" . | nindent 4 }}
{{- if .Values.prometheus.rules.labels }}
{{- toYaml .Values.prometheus.rules.labels | nindent 4 }}
{{- end }}
  name: postgres-not-enough-connections
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  groups:
  - name: postgres
    rules:
    - alert: PostgresNotEnoughConnections
      expr: sum by (datname) (pg_stat_activity_count{datname!~"template.*|postgres"}) < 5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: PostgreSQL not enough connections (instance {{`{{ $labels.instance }}`}} in cluster {{`{{$labels.cluster_name}}`}})
        description: "PostgreSQL instance should have more connections (> 5)\n  VALUE = {{`{{ $value }}`}}\n  LABELS: {{`{{ $labels }}`}}"
{{- end }}
