apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.newPvcName }}
spec:
  storageClassName: {{ .Values.newPvcStorageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.newPvcSize }}
