{{- if and ( .Values.prometheus.rules.signportPodCrashLooping ) ( .Values.prometheus.rules.signportPodCrashLooping.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: signport-pod-crash-looping
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  # If labels are defined in spec.ruleSelector.matchLabels of your deployed Prometheus object, make sure to include them here.
  labels:
    role: alert-rules
    {{- include "signport-observability.labels" . | nindent 4 }}
    {{- if .Values.prometheus.rules.labels }}
    {{- toYaml .Values.prometheus.rules.labels | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: signport
    rules:
{{- range .Values.prometheus.rules.signportPodCrashLooping.podNamePrefixList }}
    - alert: SignportPodCrashLooping-{{.}}
      expr: |
        rate(kube_pod_container_status_restarts_total{namespace=~"{{ $.Values.global.namespace | default $.Release.Namespace }}", pod=~"{{.}}.*"}[5m]) * 60 * 5 > 0
      for: 10m
      annotations:
        message: Pod {{`{{ $labels.namespace }}`}}/{{`{{ $labels.pod }}`}} ({{`{{$labels.container }}`}}) is restarting {{`{{ printf "%.2f" $value }}`}} times / 5 minutes.
      labels:
        severity: warning
{{- end }}
{{- end }}
