{{- if and ( .Values.prometheus.rules.signportContainerWaiting ) ( .Values.prometheus.rules.signportContainerWaiting.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: signport-container-waiting
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  # If labels are defined in spec.ruleSelector.matchLabels of your deployed Prometheus object, make sure to include them here.
  labels:
    role: alert-rules
    {{- include "signport-observability.labels" . | nindent 4 }}
    {{- if .Values.prometheus.rules.labels }}
    {{- toYaml .Values.prometheus.rules.labels | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: signport
    rules:
{{- range .Values.prometheus.rules.signportContainerWaiting.podNamePrefixList }}
    - alert: SignportContainerWaiting-{{.}}
      expr: |
        sum by (namespace, pod, container)
        (kube_pod_container_status_waiting_reason{namespace=~"{{ $.Values.global.namespace | default $.Release.Namespace }}", pod=~"{{.}}.*"})
        > 0
      for: 1h
      annotations:
        message: Pod {{`{{ $labels.namespace }}`}}/{{`{{ $labels.pod }}`}} container {{`{{ $labels.container }}`}} has been in waiting state for longer than 1 hour.
      labels:
        severity: warning
{{- end }}
{{- end }}
