{{- if .Values.secretUpdater.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: secret-updater
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.secretUpdater.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: updater
          containers:
            - name: updater
              image: ghcr.io/appscode/kubectl:v1.32.3
              command:
                - /bin/sh
                - -c
                - |
                  RAW=$(date '+Secret-%Y-%m-%d %H:%M:%S')
                  ENCODED=$(echo -n $RAW | base64)
                  echo "Patching Secret with $RAW"
                  kubectl patch secret demo-secret -n {{ .Values.namespace }} --type merge -p "{\"data\":{\"password\":\"$ENCODED\"}}"
          restartPolicy: OnFailure
{{- end }}
