{{- if and ( .Values.prometheus.rules ) ( .Values.prometheus.rules.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cloudnative-pg-rules
  namespace: {{ include "cloudnative-pg-observability.namespace" . }}
  labels:
    {{- include "cloudnative-pg-observability.labels" . | nindent 4 }}
spec:
  groups:
    - name: cloudnative-pg/{{ .Values.prometheus.rules.CNPGClusterName }}
      rules:
        {{- $dict := dict "excludeRules" .Values.prometheus.rules.excludeRules -}}
        {{- $_ := set $dict "value"       "{{ $value }}" -}}
        {{- $_ := set $dict "namespace"   .Release.Namespace -}}
        {{- $_ := set $dict "cluster"     .Values.prometheus.rules.CNPGClusterName -}}
        {{- $_ := set $dict "labels"      (dict "job" "{{ $labels.job }}" "node" "{{ $labels.node }}" "pod" "{{ $labels.pod }}") -}}
        {{- $_ := set $dict "podSelector" (printf "%s-([1-9][0-9]*)$" .Values.prometheus.rules.CNPGClusterName) -}}
        {{- $_ := set $dict "Values"      .Values -}}
        {{- $_ := set $dict "Template"    .Template -}}
        {{- range $path, $_ := .Files.Glob  "prometheus_rules/**.yaml" }}
        {{- $tpl := tpl ($.Files.Get $path) $dict | nindent 10 | trim -}}
        {{- with $tpl }}
        - {{ $tpl }}
        {{- end -}}
        {{- end -}}
{{ end }}
