load('ext://namespace', 'namespace_create', 'namespace_inject')

settings = read_json('../tilt-settings.json', default={})

namespace="rh-patch-operator"

namespace_create(namespace)

if settings.get("allow_k8s_contexts"):
  allow_k8s_contexts(settings.get("allow_k8s_contexts").format(namespace))

k8s_yaml(helm(
    '.',
    name='rh-patch-operator-installer',
    namespace=namespace,
    values=['values-local.yaml']))
