{{- if .Values.sealedSecret }}
{{- if .Values.sealedSecret.enabled }}
{{- range .Values.sealedSecret.files }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
{{- if $.Values.sealedSecret.labels }}
  labels:
{{ toYaml $.Values.sealedSecret.labels | indent 4 }}
{{- end }}
{{- if $.Values.sealedSecret.annotations }}
  annotations:
{{ toYaml $.Values.sealedSecret.annotations | indent 4 }}
{{- end }}
spec:
  encryptedData:
  {{- range $key, $value := .encryptedData }}
    {{ $key }}: {{ $value }}
  {{- end }}
  template:
    metadata:
      name: {{ .name }}
      namespace: {{ $.Release.Namespace }}
      {{- if $.Values.sealedSecret.annotations }}
      annotations:
     {{ toYaml $.Values.sealedSecret.annotations | indent 4 }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
