{{- if .Values.secret }}
{{- if .Values.secret.enabled }}
{{- range .Values.secret.files }}
apiVersion: v1
kind: Secret
metadata:
{{- if $.Values.secret.labels }}
  labels:
{{ toYaml $.Values.secret.labels | indent 4 }}
{{- end }}
{{- if $.Values.secret.annotations }}
  annotations:
{{ toYaml $.Values.secret.annotations | indent 4 }}
{{- end }}
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
data:
{{- range $key, $value := .data }}
  {{ $key }}: {{ $value }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
