---
{{- if and ( .Values.prometheus.monitors.serviceMonitor ) ( .Values.prometheus.monitors.serviceMonitor.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak-service-monitor
  namespace: sso
spec:
  endpoints:
    - bearerTokenSecret:
        key: ''
      path: /auth/realms/master/metrics
      port: keycloak
      scheme: https
      tlsConfig:
        ca: {}
        cert: {}
        insecureSkipVerify: true
    - bearerTokenSecret:
        key: ''
      path: /metrics
      port: keycloak-monitoring
      scheme: http
      tlsConfig:
        ca: {}
        cert: {}
        insecureSkipVerify: true
  namespaceSelector: {}
  selector:
    matchLabels:
      app: keycloak
{{- end }}
