---
{{- if and ( .Values.prometheus.rules.rabbitmq.rabbitMqDiskSpaceAlarm ) ( .Values.prometheus.rules.rabbitmq.rabbitMqDiskSpaceAlarm.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rabbitmq-disk-space-alarm
{{- if .Values.prometheus.rules.rabbitmq.rabbitMqDiskSpaceAlarm.namespace  }}
  namespace: {{ .Values.prometheus.rules.rabbitmq.rabbitMqDiskSpaceAlarm.namespace }}
{{- else }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
{{- end }}
  # If labels are defined in spec.ruleSelector.matchLabels of your deployed Prometheus object, make sure to include them here.
  labels:
    role: alert-rules
{{- if .Values.prometheus.rules.labels }}
{{- toYaml .Values.prometheus.rules.labels | nindent 4 }}
{{- end }}
spec:
  groups:
  - name: rabbitmq
    rules:
    - alert: RabbitMqDiskSpaceAlarm
      expr: rabbitmq_node_disk_free_alarm{job=~".*rabbitmq.*"} == 1
      for: 1m
      annotations:
        description: RabbitMQ {{`{{ $labels.instance }}`}} Disk Space Alarm is going off.  Which means the node hit highwater mark and has cut off network connectivity, see RabbitMQ WebUI
        summary: RabbitMQ is Out of Disk Space
      labels:
        rabbitmq_cluster: '{{`{{ $labels.label_app_kubernetes_io_name }}`}}'
        rulesgroup: rabbitmq
        severity: critical
{{- end }}