{{- if and ( .Values.prometheus.rules.rabbitmq.rabbitMqMemoryUsageHigh ) ( .Values.prometheus.rules.rabbitmq.rabbitMqMemoryUsageHigh.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rabbitmq-memory-usage-high
{{- if .Values.prometheus.rules.rabbitmq.rabbitMqMemoryUsageHigh.namespace  }}
  namespace: {{ .Values.prometheus.rules.rabbitmq.rabbitMqMemoryUsageHigh.namespace }}
{{- else }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
{{- end }}
  # If labels are defined in spec.ruleSelector.matchLabels of your deployed Prometheus object, make sure to include them here.
  labels:
    role: alert-rules
{{- if .Values.prometheus.rules.labels }}
{{- toYaml .Values.prometheus.rules.labels | nindent 4 }}
{{- end }}
spec:
  groups:
  - name: rabbitmq
    rules:
    - alert: RabbitMqMemoryUsageHigh
      expr: rabbitmq_process_resident_memory_bytes / rabbitmq_resident_memory_limit_bytes * 100 > 90
      for: 1m
      annotations:
        description: RabbitMQ {{`{{ $labels.instance }}`}} Memory Usage > 90%
        summary: RabbitMQ Node > 90% Memory Usage
      labels:
        rabbitmq_cluster: '{{`{{ $labels.label_app_kubernetes_io_name }}`}}'
        rulesgroup: rabbitmq
        severity: critical
{{- end }}