---
{{- if and ( .Values.prometheus.rules.rabbitmq.rabbitMqClusterNotAllNodesRunning ) ( .Values.prometheus.rules.rabbitmq.rabbitMqClusterNotAllNodesRunning.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rabbitmq-cluster-not-all-nodes-running
{{- if .Values.prometheus.rules.rabbitmq.rabbitMqClusterNotAllNodesRunning.namespace  }}
  namespace: {{ .Values.prometheus.rules.rabbitmq.rabbitMqClusterNotAllNodesRunning.namespace }}
{{- else }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
{{- end }}
  # If labels are defined in spec.ruleSelector.matchLabels of your deployed Prometheus object, make sure to include them here.
  labels:
    role: alert-rules
{{- if .Values.prometheus.rules.labels }}
{{- toYaml .Values.prometheus.rules.labels | nindent 4 }}
{{- end }}
spec:
  groups:
  - name: rabbitmq
    rules:
    - alert: RabbitMqClusterNotAllNodesRunning
      expr: (sum(rabbitmq_up{job=~".*rabbitmq.*"})  by (job))  < (sum(up{job=~".*rabbitmq.*"})  by (job))
      for: 1m
      annotations:
        description: Some RabbitMQ Cluster Nodes Are Down in job {{`{{ $labels.instance }}`}}/{{`{{ $labels.job}}`}}
        summary: Some RabbitMQ Cluster Nodes Are Down in job {{`{{ $labels.instance }}`}}/{{`{{ $labels.job}}`}}
      labels:
        rabbitmq_cluster: '{{`{{ $labels.label_app_kubernetes_io_name }}`}}'
        rulesgroup: rabbitmq
        severity: critical
{{- end }}