{{- if and ( .Values.prometheus.rules.errorCode ) ( .Values.prometheus.rules.errorCode.enabled ) }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: error-code
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  # If labels are defined in spec.ruleSelector.matchLabels of your deployed Prom5etheus object, make sure to include them here.
  labels:
    role: alert-rules
    namespace: {{ .Values.global.namespace | default .Release.Namespace }}
{{- if .Values.prometheus.rules.labels }}
{{- toYaml .Values.prometheus.rules.labels | nindent 4 }}
{{- end }}
spec:
  groups:
  - name: ErrorCode
    rules:
    - alert: ApiErrorCode
      expr: sum(apiserver_request_total{code=~"5..|429"})/sum(apiserver_request_total)*100 > 10
      for: 10m
      annotations:
        description: |
          More than 10 percent of the requests to the Openshift API Server for 10 minutes are returning 429 and 5xx status codes
        summary: |
          Messages are sitting idle in the queue, without any processing.
          This alert is highly application specific (and e.g. doesn't make sense for stream queues).
      labels:
        namespace: {{ .Values.global.namespace | default .Release.Namespace }}
        severity: critical
    - alert: ConsoleErrorCode
      expr: |
        sum(promhttp_metric_handler_requests_total{code=~"5..|429",namespace="openshift-console"})
        /
        sum(promhttp_metric_handler_requests_total{namespace="openshift-console"})*100 
        > 10
      for: 10m
      annotations:
        message: More than 10 percent of the requests to the Openshift Console for 10 minutes are returning 429 and 5xx status codes
      labels:
        namespace: {{ .Values.global.namespace | default .Release.Namespace }}
        severity: critical
    - alert: HAProxyErrorCode
      expr: |
        sum(promhttp_metric_handler_requests_total{code=~"5..|429",namespace="openshift-ingress"})
        /
        sum(promhttp_metric_handler_requests_total{namespace="openshift-ingress"})*100 
        > 10
      for: 10m
      annotations:
        message: More than 10 percent of the requests to the Openshift HAProxy for 10 minutes are returning 429 and 5xx status codes
      labels:
        namespace: {{ .Values.global.namespace | default .Release.Namespace }}
        severity: critical
{{- end }}
