{{- if .Values.userRoles.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: templateinstances-edit-role
rules:
  - apiGroups:
      - tenantoperator.stakater.com
    resources:
      - templateinstances
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: templateinstances-view-role
rules:
  - apiGroups:
      - tenantoperator.stakater.com
    resources:
      - templateinstances
    verbs:
      - get
      - list
      - watch
{{- end -}}
