{{- if and (.Values.pushSecret).enabled (.Capabilities.APIVersions.Has "external-secrets.io/v1alpha1") }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $backuplocation.velero.credential.name }}
  namespace: {{ include "oadp-instance.namespace" $ }}
spec:
  refreshInterval: 10s
  updatePolicy: IfNotExists
  secretStoreRefs:
    - name: stakater-cluster-secret-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: {{ $backuplocation.velero.credential.name }}
  data:
    - match:
        remoteRef:
          remoteKey: stakater/oadp/{{ $backuplocation.velero.provider }}/cloud-credentials
{{- end }}
