apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment-secret
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-deployment-secret
  template:
    metadata:
      labels:
        app: demo-deployment-secret
      annotations:
        secret.reloader.stakater.com/reload: "demo-secret"
    spec:
      containers:
        - name: echo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - 'echo "Secret: $SECRET_VALUE"; tail -f /dev/null'
          env:
            - name: SECRET_VALUE
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: password
