apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: updater
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: updater
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: updater
  apiGroup: rbac.authorization.k8s.io
