name: Pull Request

on:
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'stakater/(.*)/README.md'
      - '.github/workflows'
      - 'CODEOWNERS'

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Build
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"    

    steps:

    - name: messages
      run: |
        echo '${{toJSON(github.event.commits.*.message)}}'
        echo '${{toJSON(github.event.commits)}}'
