name: Release Helm Chart
on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
    secrets:
      REGISTRY_USERNAME:
        description: "Username for container registry to login"
        required: true

      REGISTRY_PASSWORD:
        description: "Password for container registry to login"
        required: true

jobs:
  next-version:
    uses: stakater/charts/.github/workflows/next_version.yaml@main
    with:
      component: ${{ inputs.component }}

  pull-request:
    uses: stakater/charts/.github/workflows/pull_request.yaml@main
    name: Pull Request
    if: ${{ github.ref != 'refs/heads/main' }}
    needs:
    - next-version
    secrets: inherit
    with:
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
      HELM_REGISTRY_URL: oci://ghcr.io/stakater/charts
      SUBPATH: ${{ inputs.component }}
      NEXT_VERSION: ${{ needs.next-version.outputs.version }}

  push-and-release:
    uses: stakater/charts/.github/workflows/push.yaml@main
    name: Push and Release
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs:
    - next-version
    secrets: inherit
    with:
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
      HELM_REGISTRY_URL: oci://ghcr.io/stakater/charts
      SUBPATH: ${{ inputs.component }}
      NEXT_VERSION: ${{ needs.next-version.outputs.version }}
