# Default values for redis-observability.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  namespace:

grafana:
  labels:
    grafanaDashboard: grafana-operator
  redisExporterOverview:
    enabled: true

prometheus:
  serviceMonitor:
    enabled: true
    name: redis
    port: redis-exporter
    scheme: http
    interval: 10s
    scrapeTimeout: 5s
    path: /metrics
    matchLabels: 
      app: redis
      redis_setup_type: standalone
      role: standalone
    namespaceSelector:
      any: true
  
  rules:
    labels: {}
    redisDown:
      enabled: true
    redisClusterSlotPfail:
      enabled: true
    redisClusterSlotFail:
      enabled: true
    redisClusterStateNotOk:
      enabled: true
    redisOutOfMemory:
      enabled: true
    redisTooManyConnections:
      enabled: true
      redisConnectionsThreshold: 5